// layout.js
import { Inter } from "next/font/google";

const interFont = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={interFont.className}>{children}</body>
    </html>
  )
}
